### ISSUE TITLE
KeyError: 'uri' on line `jsonSchemaURI = schemaObj["uri"]`

### ISSUE THREAD

**Issue by asweigart** [inab/python-extended-json-schema-validator#5]
On Python 3.11.0, I ran this on some json files I was trying to upload to pyvideo.org. Here is the error I got:

```
C:\github\deleteme\data>python C:\Users\Al\AppData\Local\Programs\Python\Python311\Scripts\jsonValidate.py myschema.json pybay-2016
2023-04-30 20:13:47,647 - [INFO] PASS 0.a: JSON schema loading and cache generation
2023-04-30 20:13:47,647 - [INFO] * Loading schema myschema.json
2023-04-30 20:13:47,652 - [INFO]        IGNORE: Schema in myschema.json has no id attribute
2023-04-30 20:13:47,657 - [INFO] PASS 0.b: JSON schema validation
Traceback (most recent call last):
  File "C:\Users\Al\AppData\Local\Programs\Python\Python311\Scripts\jsonValidate.py", line 7, in <module>
    main()
  File "C:\Users\Al\AppData\Local\Programs\Python\Python311\Lib\site-packages\extended_json_schema_validator\__main__.py", line 291, in main
    loadedSchemasStats = ev.loadJSONSchemasExt(args.jsonSchemaDir, verbose=isVerbose)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Al\AppData\Local\Programs\Python\Python311\Lib\site-packages\extended_json_schema_validator\extensible_validator.py", line 556, in loadJSONSchemasExt
    refSchemaListSet, valStats = self._validateJSONSchemas(
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Al\AppData\Local\Programs\Python\Python311\Lib\site-packages\extended_json_schema_validator\extensible_validator.py", line 382, in _validateJSONSchemas
    jsonSchemaURI = schemaObj["uri"]
                    ~~~~~~~~~^^^^^^^
KeyError: 'uri'
```

Here is the schema I used (myschema.json):

```
{
  "$schema":"http://json-schema.org/draft-07/schema#",
  "description":"The schema for a video record in pyvideo/data",
  "properties":{
    "alias":{
      "description":"[Deprecated] Legacy path to video on pyvideo.org",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "category":{
      "description":"[Deprecated] Category of video. This is duplicated by category files and is thus depriciated in video files.",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "copyright_text":{
      "description":"Copyright license for video or link to copyright information.",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "description":{
      "description":"reStructuredText or plain text description of video",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "duration":{
      "description":"Duration of video (in seconds)",
      "anyOf": [{"type": "null"}, {"type": "integer"}]
    },
    "id":{
      "description":"ID for video. Must be unique amongst all videos if present.",
      "anyOf": [{"type": "null"}, {"type": "integer"}]
    },
    "language":{
      "description":"ISO 639-3 language code of spoken language used in video",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "quality_notes":{
      "description":"Notes on quality of video",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "recorded":{
      "description":"ISO 8601 Date on which video was recorded (YYYY-MM-DD[Thh:mm:ss[+hh:mm]])",
      "anyOf": [
        {"type": "null"},
        {
          "type": "string",
          "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}(T[0-9]{2}:[0-9]{2}:[0-9]{2}([+-][0-9]{2}:[0-9]{2})?)?$"
        }]
    },
    "related_urls":{
      "description":"Array of related resources' URLs.",
      "items":{
        "description":"URL of resource related to video.",
        "anyOf": [{
          "type": "string",
          "format":"uri"
        }, {
          "type": "object",
          "required": ["label", "url"],
          "properties": {
            "url": {
              "type": "string",
              "format": "uri"
            },
            "label": {
              "type": "string"
            }
          }
        }]
      },
      "type":"array",
      "uniqueItems":true
    },
    "slug":{
      "description":"Web-safe slug for video. Must be unique amongst other videos in same category",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "speakers":{
      "description":"Ordered array of speakers in video.",
      "items":{
        "description":"Speaker name",
        "type":"string"
      },
      "type":"array",
      "uniqueItems":true
    },
    "summary":{
      "description":"reStructuredText or plain text description of video",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "tags":{
      "description":"Array of tags describing video",
      "items":{
        "description":"Tag describing video",
        "type":"string",
        "minLength": 1
      },
      "type": "array",
      "uniqueItems":true
    },
    "thumbnail_url":{
      "description":"URL to thumbnail for video",
      "format":"uri",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "title":{
      "description":"Title of video",
      "type":"string"
    },
    "videos":{
      "description":"Array of video locations and types",
      "items":{
        "description":"A video location and type",
        "properties":{
          "type":{
            "description":"File type of video at associated location",
            "type":"string"
          },
          "url":{
            "description":"URL for video",
            "format":"uri",
            "type":"string"
          },
          "length":{
            "description":"[Deprecated] Size of video (in bytes). Please use 'size' instead.",
            "anyOf": [{"type": "null"}, {"type": "integer"}]
          },
          "size":{
            "description":"Size of video (in bytes)",
            "anyOf": [{"type": "null"}, {"type": "integer"}]
          }
        },
        "required":[
          "type",
          "url"
        ],
        "type":"object"
      },
      "type":"array",
      "uniqueItems":true,
      "minItems": 1
    }
  },
  "required":[
    "description",
    "speakers",
    "recorded",
    "title",
    "videos"
  ],
  "title":"Video",
  "type":"object"
}
```

I get the same error when validating files that are already in pyvideo.org and pass validation, so I don't think it's my files causing this.

**Comment by jmfernandez** [comment]
Dear @asweigart , I'm glad you are interested in this extended JSON validator, because you just found a corner case.

The error message is related to the fact the JSON Schema you have tried has no `$id` (see https://json-schema.org/understanding-json-schema/basics.html#declaring-a-unique-identifier).

When this extended validator was initially created, one of its premises was to use a directory full of interrelated JSON Schemas, and zero or more JSONs. First, all the schemas are loaded and validated, which implies resolving their internal and external references. Then, the way to match which validated JSON Schema has to be used with each JSON is based either on finding some property in the JSON having the `$id` of the JSON Schema to be used, or telling the program it can "guess".

I have just released a new version, where "anonymous" JSON Schemas are assigned a random `$id` in order to be validated. Once you have updated, if you want to validate the input JSONs against your "anonymous" JSON Schema, you have to use something similar to next command line:

```bash
python jsonValidate.py --guess-schema myschema.json pybay-2016
```

There are other command-line flags and parameters you might find useful, like saving the report in a JSON file using `--report` parameter.

Hope this helps!
